### ISSUE TITLE
Conan error Exit 2  during dev_setup.py

### ISSUE THREAD

**Issue by gllmAR** [egnor/pivid#14]
Following the instruction on a fresh bulleyes (32 bite lite) install,

While running dev_setup.py I get the following error

```
=== System packages (sudo apt install ...) ===

=== Build dir (/home/pi/src/pivid/build) ===

=== Python packages (pip install ...) ===

=== C++ package manager (conan init) ===
direnv: loading ~/src/pivid/.envrc
usage: conan config [-h] [-v [V]] {home,install,list,show} ...
conan config: error: argument subcommand: invalid choice: 'init' (choose from 'home', 'install', 'list', 'show')
ERROR: Exiting with code: 2
Traceback (most recent call last):
  File "/home/pi/src/pivid/./dev_setup.py", line 56, in <module>
    run_conan("config", "init")
  File "/home/pi/src/pivid/./dev_setup.py", line 54, in run_conan
    check_call(["direnv", "exec", source_dir, "conan", *av], **kw)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['direnv', 'exec', PosixPath('/home/pi/src/pivid'), 'conan', 'config', 'init']' returned non-zero exit status 2.
``` 

Is there some thing that I missed during the install? 

Looking forward to test your software

**Comment by egnor** [comment]
Ooooh apparently Conan went from 1.x to 2.x and changed some of its commands.

I'll try to look at it in the next day or so, but meantime you could look at that script and see if there's some way to get Conan 1.x installed instead??

**Comment by gllmAR** [comment]
Installing Conan 1.59 solved this issue
```
pip install conan==1.59 
```

**Comment by minizzZ** [comment]
It gives the same problem again altough I installed conan 1.59. Did everything by the book. I work with a 4B 4GB

**Comment by egnor** [comment]
@minizzZ you may have installed that globally, not within the virtualenv that dev_setup.py creates?

I've updated the project to pin conan 1.x, so try pulling and running dev_setup.py again?
